# Generated by Django 3.1.7 on 2021-03-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
