# Generated by Django 3.1.7 on 2021-03-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='picture',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='description',
        ),
    ]
